---
format: 
  pdf:
    jwhcoverletter: default
fontsize: "12pt"
fullname: "Jeffrey W. Hollister"
email: "jeff.w.hollister@gmail.com"
linkedin: "jhollist"
phone: "401 556 4087"
citystate: "Wakefield, RI"
ymd: "`r lubridate::today()`"
company: |
  | Center for Education Policy Research
  | Harvard Graduate School of Education
recipient: "Senior Data Scientist Hiring Committee"
street: "13 Appian Way"
city: "Cambridge"
state: "MA"
zip: "02138"
greeting: "Dear"
sig: "sig.png"
closer: "Sincerely"
---

I am writing to express my interest in the Senior Data Scientist position with the Harvard Graduate School of Education. I have over 20 years of experience in data analysis, research leadership, and advanced statistical programming in R. I have developed advanced models (e.g. Random Forests) communicated the results of these to multiple audiences. A big portion of my experience has been collaborating with and mentoring others to use modern data science and open science tools in their research workflows.  Given my experience and skills, I am confident you will find that I am well-suited to the role of Senior Data Scientist.

As a researcher with the U.S. Environmental Protection Agency, I’ve led projects that span the full data lifecycle — from field collection through analysis and publication. My work includes building reproducible data architectures in R that are automated with GitHub Actions. An example of this is an effort I led to provide provisional data access from a water quality study to our project partners and the public.  The end result of this project is available at <https://github.com/usepa/provisional_habs>.

I am also an advocate and practitioner of open science. Through my roles at EPA and as adjunct faculty at the University of Rhode Island, I’ve trained hundreds of scientists in open-source tools and principles. I co-developed and maintain several R packages used internationally for lake morphometry, and elevation data extraction from APIs (i.e., the `elevatr` pacakge: <https://CRAN.R-project.org/package=elevatr>).

Beyond technical capabilities, I bring leadership and collaborative experience. I’ve supervised teams, advised on data management strategies, and contributed to agency-level and inter-agency initiatives, including serving on the White House's Office of Science and Technology Policy subgroup on the Year of Open Science. I’m passionate about translating complex datasets into meaningful insights as shown by my publication and presentation record. 

I welcome the opportunity to discuss how I can contribute. Thank you for considering my application.